
package Show;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Hashtable;
import static java.util.Objects.hash;
import javax.swing.JOptionPane;

public class PanelPrin extends javax.swing.JFrame {
    int XMouse, YMouse;
    
    HashMap<String, Estudiantes> map;//Gestion estudiantes
    public PanelPrin() {
        initComponents();
        this.setVisible(true);
        map=new HashMap<String,Estudiantes>();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel25 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Regis_panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Bus_panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Dev_panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Act_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Exit_panel = new javax.swing.JPanel();
        Panel_sal = new javax.swing.JPanel();
        Exid_label = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        NP_field = new javax.swing.JTextField();
        CP_field = new javax.swing.JTextField();
        NS_field = new javax.swing.JTextField();
        FS_field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RTA_field = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        FS_field2 = new javax.swing.JTextField();
        CP_field4 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CP_fieldB = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        RTA_fieldB = new javax.swing.JTextArea();
        buscar_button = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        RTA_field1 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        CP_field1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        NP_field1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        NS_field1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        FS_field1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        FS_field3 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CP_fieldBD = new javax.swing.JTextField();
        devolver_button = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        RTA_fieldD = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        jLabel25.setText("jLabel25");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(63, 47, 54));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 123, 115));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Regis_panel.setBackground(new java.awt.Color(204, 123, 115));
        Regis_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Regis_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Regis_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Regis_panelMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(63, 47, 54));
        jLabel3.setText("REGISTRO");

        javax.swing.GroupLayout Regis_panelLayout = new javax.swing.GroupLayout(Regis_panel);
        Regis_panel.setLayout(Regis_panelLayout);
        Regis_panelLayout.setHorizontalGroup(
            Regis_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Regis_panelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Regis_panelLayout.setVerticalGroup(
            Regis_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Regis_panelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel2.add(Regis_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 170, 200, -1));

        Bus_panel.setBackground(new java.awt.Color(204, 123, 115));
        Bus_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bus_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bus_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bus_panelMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(63, 47, 54));
        jLabel4.setText("BUSCAR");

        javax.swing.GroupLayout Bus_panelLayout = new javax.swing.GroupLayout(Bus_panel);
        Bus_panel.setLayout(Bus_panelLayout);
        Bus_panelLayout.setHorizontalGroup(
            Bus_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Bus_panelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Bus_panelLayout.setVerticalGroup(
            Bus_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Bus_panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.add(Bus_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 208, -1));

        Dev_panel.setBackground(new java.awt.Color(204, 123, 115));
        Dev_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Dev_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Dev_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Dev_panelMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(63, 47, 54));
        jLabel5.setText("ACTUALIZAR");

        javax.swing.GroupLayout Dev_panelLayout = new javax.swing.GroupLayout(Dev_panel);
        Dev_panel.setLayout(Dev_panelLayout);
        Dev_panelLayout.setHorizontalGroup(
            Dev_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dev_panelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        Dev_panelLayout.setVerticalGroup(
            Dev_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dev_panelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel2.add(Dev_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, -1));

        Act_panel.setBackground(new java.awt.Color(204, 123, 115));
        Act_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Act_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Act_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Act_panelMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(63, 47, 54));
        jLabel2.setText("ELIMINAR");

        javax.swing.GroupLayout Act_panelLayout = new javax.swing.GroupLayout(Act_panel);
        Act_panel.setLayout(Act_panelLayout);
        Act_panelLayout.setHorizontalGroup(
            Act_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Act_panelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        Act_panelLayout.setVerticalGroup(
            Act_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Act_panelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel2.add(Act_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 208, -1));
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 12, -1, 152));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labo/ICON.png"))); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 160));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 530));

        Exit_panel.setBackground(new java.awt.Color(165, 74, 85));
        Exit_panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Exit_panelMouseDragged(evt);
            }
        });
        Exit_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Exit_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit_panelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Exit_panelMousePressed(evt);
            }
        });

        Panel_sal.setBackground(new java.awt.Color(165, 74, 85));
        Panel_sal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_salMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_salMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_salMouseExited(evt);
            }
        });

        Exid_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Exid_label.setForeground(new java.awt.Color(214, 182, 186));
        Exid_label.setText(" X");
        Exid_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Exid_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Exid_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exid_labelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel_salLayout = new javax.swing.GroupLayout(Panel_sal);
        Panel_sal.setLayout(Panel_salLayout);
        Panel_salLayout.setHorizontalGroup(
            Panel_salLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_salLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Exid_label)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        Panel_salLayout.setVerticalGroup(
            Panel_salLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_salLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Exid_label, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Exit_panelLayout = new javax.swing.GroupLayout(Exit_panel);
        Exit_panel.setLayout(Exit_panelLayout);
        Exit_panelLayout.setHorizontalGroup(
            Exit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Exit_panelLayout.createSequentialGroup()
                .addContainerGap(475, Short.MAX_VALUE)
                .addComponent(Panel_sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Exit_panelLayout.setVerticalGroup(
            Exit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_sal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(Exit_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 530, 50));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 50, 50));

        jTabbedPane1.setBackground(new java.awt.Color(63, 47, 54));
        jTabbedPane1.setForeground(new java.awt.Color(63, 47, 54));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setVerifyInputWhenFocusTarget(false);

        jPanel5.setBackground(new java.awt.Color(63, 47, 54));
        jPanel5.setPreferredSize(new java.awt.Dimension(530, 480));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NP_field.setBackground(new java.awt.Color(214, 182, 186));
        NP_field.setForeground(new java.awt.Color(63, 47, 54));
        NP_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NP_fieldActionPerformed(evt);
            }
        });
        jPanel5.add(NP_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 196, 30));

        CP_field.setBackground(new java.awt.Color(214, 182, 186));
        CP_field.setForeground(new java.awt.Color(63, 47, 54));
        CP_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CP_fieldActionPerformed(evt);
            }
        });
        jPanel5.add(CP_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 196, 30));

        NS_field.setBackground(new java.awt.Color(214, 182, 186));
        NS_field.setForeground(new java.awt.Color(63, 47, 54));
        jPanel5.add(NS_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 196, 30));

        FS_field.setBackground(new java.awt.Color(214, 182, 186));
        FS_field.setForeground(new java.awt.Color(63, 47, 54));
        FS_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FS_fieldActionPerformed(evt);
            }
        });
        jPanel5.add(FS_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 196, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(234, 162, 152));
        jLabel1.setText("REGISTRO DE ESTUDIANTES");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel6.setForeground(new java.awt.Color(214, 182, 186));
        jLabel6.setText("Nombre: ");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        jLabel7.setForeground(new java.awt.Color(214, 182, 186));
        jLabel7.setText("Apellido:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        jLabel8.setForeground(new java.awt.Color(214, 182, 186));
        jLabel8.setText("Numero de Telefono:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 20));

        jLabel9.setForeground(new java.awt.Color(214, 182, 186));
        jLabel9.setText("Direccion:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 20));

        RTA_field.setEditable(false);
        RTA_field.setBackground(new java.awt.Color(214, 182, 186));
        RTA_field.setColumns(20);
        RTA_field.setForeground(new java.awt.Color(63, 47, 54));
        RTA_field.setRows(5);
        jScrollPane1.setViewportView(RTA_field);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 82, 271, 340));

        jButton1.setBackground(new java.awt.Color(204, 123, 115));
        jButton1.setForeground(new java.awt.Color(63, 47, 54));
        jButton1.setText("Registro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 123, 115));
        jButton2.setForeground(new java.awt.Color(63, 47, 54));
        jButton2.setText("Mostrar Registro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 196, -1));

        jLabel23.setForeground(new java.awt.Color(214, 182, 186));
        jLabel23.setText("Carrera:");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 20));

        FS_field2.setBackground(new java.awt.Color(214, 182, 186));
        FS_field2.setForeground(new java.awt.Color(63, 47, 54));
        jPanel5.add(FS_field2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 196, 30));

        CP_field4.setBackground(new java.awt.Color(214, 182, 186));
        CP_field4.setForeground(new java.awt.Color(63, 47, 54));
        CP_field4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CP_field4ActionPerformed(evt);
            }
        });
        jPanel5.add(CP_field4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 196, 30));

        jLabel27.setForeground(new java.awt.Color(214, 182, 186));
        jLabel27.setText("Codigo: ");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        jTabbedPane1.addTab("tab1", jPanel5);

        jPanel6.setBackground(new java.awt.Color(63, 47, 54));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(234, 162, 152));
        jLabel10.setText("BUSQUEDA DE CONTACTOS");

        jLabel11.setForeground(new java.awt.Color(214, 182, 186));
        jLabel11.setText("Nombre:");

        CP_fieldB.setBackground(new java.awt.Color(214, 182, 186));
        CP_fieldB.setForeground(new java.awt.Color(63, 47, 54));

        RTA_fieldB.setBackground(new java.awt.Color(214, 182, 186));
        RTA_fieldB.setColumns(20);
        RTA_fieldB.setForeground(new java.awt.Color(63, 47, 54));
        RTA_fieldB.setRows(5);
        jScrollPane2.setViewportView(RTA_fieldB);

        buscar_button.setBackground(new java.awt.Color(204, 123, 115));
        buscar_button.setForeground(new java.awt.Color(63, 47, 54));
        buscar_button.setText("Buscar");
        buscar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_buttonActionPerformed(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labo/YD1.png"))); // NOI18N
        jLabel21.setText("jLabel21");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(118, 118, 118))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscar_button)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CP_fieldB)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addGap(21, 21, 21)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(CP_fieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscar_button)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel6);

        jPanel8.setBackground(new java.awt.Color(63, 47, 54));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(234, 162, 152));
        jLabel14.setText("ACTUALIZAR INFORMACION");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jButton3.setBackground(new java.awt.Color(204, 123, 115));
        jButton3.setForeground(new java.awt.Color(63, 47, 54));
        jButton3.setText("Acutalizar datos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        jButton4.setBackground(new java.awt.Color(204, 123, 115));
        jButton4.setForeground(new java.awt.Color(63, 47, 54));
        jButton4.setText("Mostrar lista actual");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 166, -1));

        RTA_field1.setEditable(false);
        RTA_field1.setBackground(new java.awt.Color(214, 182, 186));
        RTA_field1.setColumns(20);
        RTA_field1.setForeground(new java.awt.Color(63, 47, 54));
        RTA_field1.setRows(5);
        jScrollPane4.setViewportView(RTA_field1);

        jPanel8.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 270, 380));

        jLabel15.setForeground(new java.awt.Color(214, 182, 186));
        jLabel15.setText("Nombre: ");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        CP_field1.setBackground(new java.awt.Color(214, 182, 186));
        CP_field1.setForeground(new java.awt.Color(63, 47, 54));
        CP_field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CP_field1ActionPerformed(evt);
            }
        });
        jPanel8.add(CP_field1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 196, -1));

        jLabel16.setForeground(new java.awt.Color(214, 182, 186));
        jLabel16.setText("Apellido:");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        NP_field1.setBackground(new java.awt.Color(214, 182, 186));
        NP_field1.setForeground(new java.awt.Color(63, 47, 54));
        NP_field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NP_field1ActionPerformed(evt);
            }
        });
        jPanel8.add(NP_field1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 196, -1));

        jLabel17.setForeground(new java.awt.Color(214, 182, 186));
        jLabel17.setText("Numero de Telefono:");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        NS_field1.setBackground(new java.awt.Color(214, 182, 186));
        NS_field1.setForeground(new java.awt.Color(63, 47, 54));
        jPanel8.add(NS_field1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 196, -1));

        jLabel18.setForeground(new java.awt.Color(214, 182, 186));
        jLabel18.setText("Direccion:");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        FS_field1.setBackground(new java.awt.Color(214, 182, 186));
        FS_field1.setForeground(new java.awt.Color(63, 47, 54));
        jPanel8.add(FS_field1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 196, -1));

        jLabel24.setForeground(new java.awt.Color(214, 182, 186));
        jLabel24.setText("Carrera:");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        FS_field3.setBackground(new java.awt.Color(214, 182, 186));
        FS_field3.setForeground(new java.awt.Color(63, 47, 54));
        jPanel8.add(FS_field3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 196, -1));

        jTabbedPane1.addTab("tab4", jPanel8);

        jPanel7.setBackground(new java.awt.Color(63, 47, 54));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(234, 162, 152));
        jLabel12.setText("ELIMINAR CONTACTOS");

        jLabel13.setForeground(new java.awt.Color(214, 182, 186));
        jLabel13.setText("Nombre: ");

        CP_fieldBD.setBackground(new java.awt.Color(214, 182, 186));
        CP_fieldBD.setForeground(new java.awt.Color(63, 47, 54));

        devolver_button.setBackground(new java.awt.Color(204, 123, 115));
        devolver_button.setForeground(new java.awt.Color(63, 47, 54));
        devolver_button.setText("Eliminar");
        devolver_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolver_buttonActionPerformed(evt);
            }
        });

        RTA_fieldD.setBackground(new java.awt.Color(214, 182, 186));
        RTA_fieldD.setColumns(20);
        RTA_fieldD.setForeground(new java.awt.Color(63, 47, 54));
        RTA_fieldD.setRows(5);
        jScrollPane3.setViewportView(RTA_fieldD);

        jButton5.setBackground(new java.awt.Color(204, 123, 115));
        jButton5.setForeground(new java.awt.Color(63, 47, 54));
        jButton5.setText("Mostrar lista actual");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Labo/YD2.png"))); // NOI18N
        jLabel20.setText("jLabel20");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(devolver_button)
                            .addComponent(jLabel13)
                            .addComponent(CP_fieldBD, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(133, 133, 133))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(CP_fieldBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(devolver_button)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", jPanel7);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 530, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Regis_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regis_panelMouseEntered
        // TODO add your handling code here:
        Regis_panel.setBackground(new Color(214,182,186));
        
    }//GEN-LAST:event_Regis_panelMouseEntered

    private void Exid_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exid_labelMouseEntered
        // TODO add your handling code here:
        Panel_sal.setBackground(new Color(204,123,115));
    }//GEN-LAST:event_Exid_labelMouseEntered

    private void Regis_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regis_panelMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_Regis_panelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            registrarPersona(map);    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buscar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_buttonActionPerformed
        // TODO add your handling code here:
        buscarPersona(map);
    }//GEN-LAST:event_buscar_buttonActionPerformed

    private void devolver_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolver_buttonActionPerformed
        // TODO add your handling code here:
        Eliminar(map);
    }//GEN-LAST:event_devolver_buttonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ActualizarInfo(map);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        mostrarRegistro(map);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        mostrarRegistroD(map);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        mostrarRegistroA(map);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Regis_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regis_panelMouseExited
        // TODO add your handling code here:
        Regis_panel.setBackground(new Color(204,123,115));
    }//GEN-LAST:event_Regis_panelMouseExited

    private void Exid_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exid_labelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Exid_labelMouseClicked

    private void Exit_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit_panelMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Exit_panelMouseEntered

    private void Exit_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit_panelMouseExited
        // TODO add your handling code here:
      
    }//GEN-LAST:event_Exit_panelMouseExited

    private void Panel_salMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_salMouseEntered
        // TODO add your handling code here:
        Panel_sal.setBackground(new Color(204,123,115));
    }//GEN-LAST:event_Panel_salMouseEntered

    private void Panel_salMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_salMouseExited
        // TODO add your handling code here:
        Panel_sal.setBackground(new Color(165,74,85));
    }//GEN-LAST:event_Panel_salMouseExited

    private void Panel_salMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_salMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Panel_salMouseClicked

    private void Exid_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exid_labelMouseExited
        // TODO add your handling code here:
        Panel_sal.setBackground(new Color(165,74,85));
    }//GEN-LAST:event_Exid_labelMouseExited

    private void Bus_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bus_panelMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_Bus_panelMouseClicked

    private void Dev_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dev_panelMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_Dev_panelMouseClicked

    private void Act_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Act_panelMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_Act_panelMouseClicked

    private void Bus_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bus_panelMouseEntered
        // TODO add your handling code here:
        Bus_panel.setBackground(new Color(214,182,186));
    }//GEN-LAST:event_Bus_panelMouseEntered

    private void Dev_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dev_panelMouseEntered
        // TODO add your handling code here:
        Dev_panel.setBackground(new Color(214,182,186));
    }//GEN-LAST:event_Dev_panelMouseEntered

    private void Act_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Act_panelMouseEntered
        // TODO add your handling code here:
        Act_panel.setBackground(new Color(214,182,186));
    }//GEN-LAST:event_Act_panelMouseEntered

    private void Bus_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bus_panelMouseExited
        // TODO add your handling code here:
        Bus_panel.setBackground(new Color(204,123,115));
    }//GEN-LAST:event_Bus_panelMouseExited

    private void Dev_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dev_panelMouseExited
        // TODO add your handling code here:
        Dev_panel.setBackground(new Color(204,123,115));
    }//GEN-LAST:event_Dev_panelMouseExited

    private void Act_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Act_panelMouseExited
        // TODO add your handling code here:
        Act_panel.setBackground(new Color(204,123,115));
    }//GEN-LAST:event_Act_panelMouseExited

    private void Exit_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit_panelMousePressed
        // TODO add your handling code here:
        XMouse=evt.getX();
        YMouse=evt.getY();
    }//GEN-LAST:event_Exit_panelMousePressed

    private void Exit_panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit_panelMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-XMouse, y-YMouse);
    }//GEN-LAST:event_Exit_panelMouseDragged

    private void NP_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NP_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NP_fieldActionPerformed

    private void CP_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CP_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CP_fieldActionPerformed

    private void CP_field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CP_field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CP_field1ActionPerformed

    private void NP_field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NP_field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NP_field1ActionPerformed

    private void FS_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FS_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FS_fieldActionPerformed

    private void CP_field4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CP_field4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CP_field4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPrin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Act_panel;
    private javax.swing.JPanel Bus_panel;
    private javax.swing.JTextField CP_field;
    private javax.swing.JTextField CP_field1;
    private javax.swing.JTextField CP_field4;
    private javax.swing.JTextField CP_fieldB;
    private javax.swing.JTextField CP_fieldBD;
    private javax.swing.JPanel Dev_panel;
    private javax.swing.JLabel Exid_label;
    private javax.swing.JPanel Exit_panel;
    private javax.swing.JTextField FS_field;
    private javax.swing.JTextField FS_field1;
    private javax.swing.JTextField FS_field2;
    private javax.swing.JTextField FS_field3;
    private javax.swing.JTextField NP_field;
    private javax.swing.JTextField NP_field1;
    private javax.swing.JTextField NS_field;
    private javax.swing.JTextField NS_field1;
    private javax.swing.JPanel Panel_sal;
    private javax.swing.JTextArea RTA_field;
    private javax.swing.JTextArea RTA_field1;
    private javax.swing.JTextArea RTA_fieldB;
    private javax.swing.JTextArea RTA_fieldD;
    private javax.swing.JPanel Regis_panel;
    private javax.swing.JButton buscar_button;
    private javax.swing.JButton devolver_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private void registrarPersona(HashMap<String, Estudiantes> map) {
        Estudiantes produc = new Estudiantes();
        String cod = (CP_field4.getText());
        produc.setNombre(CP_field.getText());
        produc.setApellido(NP_field.getText());
        produc.setDireccion(FS_field.getText());
        produc.setTelefono(NS_field.getText()); 
        produc.setCarrera(FS_field2.getText()); 
        
        
        if(map.containsKey(cod)==false){
            map.put(cod, produc);
            JOptionPane.showMessageDialog(null,"Contacto registrado");
        }else{
            RTA_field.setText("Contacto no registrado, ya existente");
        }
        CP_field.setText("");
        NP_field.setText("");
        NS_field.setText("");
        FS_field.setText("");
        FS_field2.setText("");
        CP_field4.setText("");
    }

    private void mostrarRegistro(HashMap<String, Estudiantes> map) {
        String mensaje ="";
        Collection<Estudiantes> values = map.values(); // obtiene la vista de los valores
        for (Estudiantes ob : values) {
            mensaje+="Nombre: " + ob.getNombre()+"\n";
            mensaje+="Apellido: " + ob.getApellido()+"\n";
            mensaje+="Direccion: " + ob.getDireccion()+"\n";
            mensaje+="Telefono: " + ob.getTelefono()+"\n";
            mensaje+="Carrera: " + ob.getCarrera()+"\n\n";
        }
        
        RTA_field.setText(mensaje); 
    }

    private void buscarPersona(HashMap<String, Estudiantes> map) {
        String mensaje = "DATOS DE CONTACTO \n";
        String codB = CP_fieldB.getText();
        if(map.containsKey(codB)==true){
            Estudiantes ob =map.get(codB);
            mensaje+="Codigo: " + codB +"\n";
            mensaje+="Nombre: " + ob.getNombre()+"\n";
            mensaje+="Apellido: " + ob.getApellido()+"\n";
            mensaje+="Direccion: " + ob.getDireccion()+"\n";
            mensaje+="Telefono: " + ob.getTelefono()+"\n";
            mensaje+="Carrera: " + ob.getCarrera()+"\n\n";
         
            
            RTA_fieldB.setText(mensaje); 
        }else{
            RTA_fieldB.setText("Contacto no encontrado");
        }
    }

    private void Eliminar(HashMap<String, Estudiantes> map) {
        String codB = CP_fieldBD.getText();
        if(map.containsKey(codB)){
            map.remove(codB);
            JOptionPane.showMessageDialog(null,"Contacto Eliminado Con Éxito");           
        }else{
            RTA_fieldD.setText("Contacto no existente");
        }
    }

    private void mostrarRegistroD(HashMap<String, Estudiantes> map) {
        String mensaje ="";        
        Collection<Estudiantes> value = map.values();
        for (Estudiantes ob : value) {
            mensaje+="Nombre: " + ob.getNombre()+"\n";
            mensaje+="Apellido: " + ob.getApellido()+"\n";
            mensaje+="Direccion: " + ob.getDireccion()+"\n";
            mensaje+="Telefono: " + ob.getTelefono()+"\n";
            mensaje+="Carrera: " + ob.getCarrera()+"\n\n";
        }
        
        RTA_fieldD.setText(mensaje); 
    }

    private void ActualizarInfo(HashMap<String, Estudiantes> map) {
        String codB = JOptionPane.showInputDialog("Ingrese el codigo del contacto");
        if(map.containsKey(codB)){
            Estudiantes producto = map.get(codB);
            String nomN = CP_field1.getText();
            String apeN = NP_field1.getText();
            String dirN = FS_field1.getText();
            String telN = NS_field1.getText();
            String carN = FS_field3.getText();
            producto.setNombre(nomN);
            producto.setApellido(apeN);
            producto.setDireccion(dirN);
            producto.setDireccion(telN);
            producto.setTelefono(telN);
            producto.setCarrera(carN);

            String mensaje = "Contacto actualizado\n";
            
            RTA_field1.setText(mensaje); 
        }else{
            RTA_field1.setText("Contacto no existente");
        }
    }

    private void mostrarRegistroA(HashMap<String, Estudiantes> map) {
        String mensaje ="";
        
        Collection<Estudiantes> value = map.values();
        for (Estudiantes ob : value) {
            mensaje+="Nombre del contacto: " + ob.getNombre()+"\n";
            mensaje+="Apellido del contacto: " + ob.getApellido()+"\n";
            mensaje+="Direccion: " + ob.getDireccion()+"\n";
            mensaje+="Telefono: " + ob.getTelefono()+"\n";
            mensaje+="Carrera: " + ob.getCarrera()+"\n\n";
        }
        
        RTA_field1.setText(mensaje); 
    }

    private void setUndecoreted(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
}
